#if defined(sevenlinedigital_font)
#include "fonts/sevenlinedigital_font.h"
#elif defined(acme_5_outlines_font)
#include "fonts/acme_5_outlines_font.h"
#elif defined(aztech_font)
#include "fonts/aztech_font.h"
#elif defined(Blokus_font)
#include "fonts/Blokus_font.h"
#elif defined(BMplain_font)
#include "fonts/BMplain_font.h"
#elif defined(BMSPA_font)
#include "fonts/BMSPA_font.h"
#elif defined(bubblesstandard_font)
#include "fonts/bubblesstandard_font.h"
#elif defined(Commo)
#include "fonts/Commo-Monospaced_font.h"
#elif defined(crackers_font)
#include "fonts/crackers_font.h"
#elif defined(font)
#include "fonts/font.h"
#elif defined(formplex12_font)
#include "fonts/formplex12_font.h"
#elif defined(haiku_font)
#include "fonts/haiku_font.h"
#elif defined(HISKYF21_font)
#include "fonts/HISKYF21_font.h"
#elif defined(homespun_font)
#include "fonts/homespun_font.h"
#elif defined(HUNTER_font)
#include "fonts/HUNTER_font.h"
#elif defined(m38_font)
#include "fonts/m38_font.h"
#elif defined(Minimum)
#include "fonts/Minimum+1_font.h"
#elif defined(Minimum_font)
#include "fonts/Minimum_font.h"
#elif defined(pzim3x5_font)
#include "fonts/pzim3x5_font.h"
#elif defined(Raumsond_font)
#include "fonts/Raumsond_font.h"
#elif defined(renew_font)
#include "fonts/renew_font.h"
#elif defined(sloth_font)
#include "fonts/sloth_font.h"
#elif defined(SUPERDIG_font)
#include "fonts/SUPERDIG_font.h"
#elif defined(tama_mini02_font)
#include "fonts/tama_mini02_font.h"
#elif defined(zxpix_font)
#include "fonts/zxpix_font.h"
#else
#include "fonts/tama_mini02_font.h"
#endif
